#!/bin/bash

LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

BUMP="patch"
[[ $(git log --pretty="%s" ^$LATEST_TAG $DEVELOP_BRANCH | grep "^fix.*\:") ]] && BUMP="patch"
[[ $(git log --pretty="%s" ^$LATEST_TAG $DEVELOP_BRANCH | grep "^refactor.*\:") ]] && BUMP="patch"
[[ $(git log --pretty="%s" ^$LATEST_TAG $DEVELOP_BRANCH | grep "^feat.*\:") ]] && BUMP="minor"
[[ $(git log --pretty="%s" ^$LATEST_TAG $DEVELOP_BRANCH | grep "^BREAKING CHANGE.*\:") ]] && BUMP="major"
[[ $(git log --pretty="%s" ^$LATEST_TAG $DEVELOP_BRANCH | grep "!\:") ]] && BUMP="major"

echo $BUMP
